### ISSUE TITLE
Give each Username an HREF that redirects to the User's Profile. 

### ISSUE THREAD

**Issue by fuzzydragon** [7RingsOfSaturn/Roblox-Mutual-Friends-Plugin#2]
This feature request is being made due to [this ](https://github.com/7RingsOfSaturn/Roblox-Mutual-Friends-Plugin/pull/1)pull request being denied. 

When viewing a profile, consider making each username listed an **\<a>** tag and setting to href to redirect to their profile.
Make sure to turn that nasty link highlighting off.

https://stackoverflow.com/questions/5233316/disable-link-highlighting/5233373

**Comment by peyton2465** [comment]
retard

**Comment by fuzzydragon** [comment]
Patch added.
* 84fb8befc0735401d66f0784b65f6a75a097675e
* 2bfb9a133b1b6abd27b8809ca03277d06d9b9e48
